version: '2'
services:
  api:
    build: ./api
    command: npm start
    volumes:
    - ./api:/usr/app/src
    - /usr/app/src/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      PORT: 3000
      DATABASE_URL: mongodb://shortenapp@mongo/shorten
  mongo:
    image: mongo:3.6
    environment:
      MONGO_USER: shortenapp
      MONGO_DB: shorten